import{a as B,S as $,i as d}from"./assets/vendor-frHSA4Lh.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function y(r,e){const n=new URLSearchParams({key:"50818565-86d44cf91814c3f45e3f7ee49",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e});return(await B(`https://pixabay.com/api/?${n}`)).data}const L=document.querySelector("#loader-top"),b=document.querySelector("#loader-bottom"),m=document.querySelector(".btn-load"),v=new $(".gallery a");function w(r){return r.map(({webformatURL:e,largeImageURL:n,tags:i,likes:t,views:o,comments:a,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${e}" alt="${i}" />
        </a>
        <div class="card">
          <p><span>👍 Likes</span>${t}</p>
          <p><span>👁 Views</span>${o}</p>
          <p><span>💬 Comments</span>${a}</p>
          <p><span>⬇ Downloads</span>${q}</p>
        </div>
      </li>
    `).join("")}function c(){const r=document.querySelector(".gallery");r.innerHTML=""}function M(){L.classList.remove("hidden")}function p(){L.classList.add("hidden")}function P(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function u(){m.classList.add("hidden")}function T(){m.classList.remove("hidden")}function E(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}const S=document.querySelector(".gallery"),H=document.querySelector(".form");let s=1,O=15,g,l,f;H.addEventListener("submit",R);async function R(r){if(r.preventDefault(),c(),s=1,M(),u(),l=r.target.elements[0].value.trim(),!!l)try{const e=await y(l,s);if(g=e.totalHits,f=Math.ceil(g/O),s<f&&T(),e.hits.length===0){p(),u(),c(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}S.innerHTML=w(e.hits),v.refresh(),p()}catch(e){console.error("Error:",e),p(),c(),d.error({message:"Error loading images",position:"topRight"})}}m.addEventListener("click",x);async function x(r){P(),s+=1;try{const e=await y(l,s);S.insertAdjacentHTML("beforeend",w(e.hits)),v.refresh(),h(),E(),s>=f&&(u(),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c(),h(),u(),d.error({message:"Error loading images",position:"topRight"})}}
//# sourceMappingURL=index.js.map
