import{a as B,S as P,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function y(r,e){const n=new URLSearchParams({key:"50818565-86d44cf91814c3f45e3f7ee49",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e});return(await B(`https://pixabay.com/api/?${n}`)).data}const L=document.querySelector("#loader-top"),b=document.querySelector("#loader-bottom"),m=document.querySelector(".btn-load"),w=new P(".gallery a");function v(r){return r.map(({webformatURL:e,largeImageURL:n,tags:a,likes:t,views:o,comments:i,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${e}" alt="${a}" />
        </a>
        <div class="card">
          <p><span>👍 Likes</span>${t}</p>
          <p><span>👁 Views</span>${o}</p>
          <p><span>💬 Comments</span>${i}</p>
          <p><span>⬇ Downloads</span>${q}</p>
        </div>
      </li>
    `).join("")}function d(){const r=document.querySelector(".gallery");r.innerHTML=""}function $(){L.classList.remove("hidden")}function l(){L.classList.add("hidden")}function M(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function p(){m.classList.add("hidden")}function R(){m.classList.remove("hidden")}function T(){const r=document.querySelector(".gallery-item");if(!r)return;const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}const S=document.querySelector(".gallery"),E=document.querySelector(".form");let s=1,H=15,g,u,f;E.addEventListener("submit",O);async function O(r){if(r.preventDefault(),d(),s=1,$(),p(),u=r.target.elements[0].value.trim(),!u){l(),c.warning({message:"Please enter a search term.",position:"topRight"});return}try{const e=await y(u,s);if(g=e.totalHits,f=Math.ceil(g/H),s<f&&R(),e.hits.length===0){l(),p(),d(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}S.innerHTML=v(e.hits),w.refresh(),l()}catch(e){console.error("Error:",e),l(),d(),c.error({message:"Error loading images",position:"topRight"})}}m.addEventListener("click",x);async function x(r){M(),s+=1;try{const e=await y(u,s);S.insertAdjacentHTML("beforeend",v(e.hits)),w.refresh(),h(),T(),s>=f&&(p(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{d(),h(),p(),c.error({message:"Error loading images",position:"topRight"})}}
//# sourceMappingURL=index.js.map
